name: Run main Python script

on:
  push:
    tags:
      - '[0-9]+.[0-9]+.[0-9]+-run'

jobs:
  optimize-random-forest:
    runs-on: ubuntu-latest
    timeout-minutes: 4320

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download fr_core_news_sm

      - name: Run Python script
        run: |
          python ./src/__main__.py optimize_random_forest

      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: results_directory_random_forest
          path: ./results/random_forest_results

  optimize-k-nearest-neighbors:
    runs-on: ubuntu-latest
    timeout-minutes: 4320

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          python -m spacy download fr_core_news_sm

      - name: Run Python script
        run: |
          python ./src/__main__.py optimize_k_nearest_neighbors

      - name: Upload result
        uses: actions/upload-artifact@v2
        with:
          name: results_directory_k_nearest_neighbors
          path: ./results/k_nearest_neighbors_results
